import csv
U="use-obj.c:"
R=[]
def a(t,k,l,e,c,aw,ci): R.append((t,k,l,e,c,aw,ci))
S="scroll"
a(S,"Light",0,"lite_area 2d8 dmg rad 2 to light-sensitive monsters, lights room","HARMLESS","yes always (lite_area returns TRUE, spells2.c:4537-4552)",U+"896")
a(S,"Treasure Detection",0,"detect gold nearby","GOOD","only if gold/objects found",U+"909")
a(S,"Object Detection",0,"detect objects nearby","GOOD","only if objects found",U+"916")
a(S,"Identify",1,"asks which item to ID; cancel keeps scroll","GOOD","yes always",U+"823")
a(S,"Summon Monster",1,"loop k<randint1(3) re-rolled each pass: 1/2/3 monsters = 33/44/22% (mean 1.9); each picked at level (dlv+dlv)/2+5 = dlv+5, placed awake, groups allowed (monster2.c:2552-2594)","DANGEROUS","only if a monster placed",U+"763")
a(S,"Phase Door",1,"teleport 10 squares (min 5)","HARMLESS","yes",U+"795")
a(S,"Detect Invisible",1,"detect invisible monsters","HARMLESS","only if one found",U+"935")
a(S,"Darkness",1,"blind 3+1d5 turns (no resist: Half-Orc resists dark, not blind) + unlight radius 3; cannot read scrolls while blind","NUISANCE","yes always (spells2.c:4562)",U+"733")
a(S,"Blessing",1,"bless 1d12+6 turns","HARMLESS","if newly blessed",U+"947")
a(S,"Monster Confusion",5,"next melee hit confuses monster","HARMLESS","yes if not already set",U+"965")
a(S,"Magic Mapping",5,"map local area (52x23 half-box)","GOOD","yes always",U+"902")
a(S,"Trap Detection",5,"detect traps","HARMLESS","only if traps found",U+"922")
a(S,"Door/Stair Location",5,"detect secret doors (detect_sdoor; stairs call commented out)","HARMLESS","only if found",U+"928")
a(S,"Aggravate Monster",5,"wakes all monsters within 40 grids on level; every monster in LOS gets speed raised to race speed+10 permanently (spells2.c:3313-3362)","DANGEROUS","yes always",U+"743")
a(S,"Satisfy Hunger",5,"food set to max-1","HARMLESS","if food changed",U+"941")
a(S,"Word of Recall",5,"sets recall: yanks to town in 15-34 player turns when in dungeon (to max depth when in town); reading again cancels (spells2.c:1135-1190, dungeon.c:1626-1700)","NUISANCE","yes always",U+"816")
a(S,"Remove Curse",10,"uncurses worn items except HEAVY_CURSE/PERMA_CURSE; no failure roll (spells2.c:467,415-445)","GOOD","only if something uncursed",U+"837")
a(S,"Teleportation",10,"teleport up to 100 squares (min 50)","HARMLESS","yes",U+"802")
a(S,"Trap Creation",10,"places INVISIBLE traps on naked floor grids radius 1 (not own grid); type rolled when stepped on/found: 16 kinds (trap door, pits, summon rune, teleport rune, fire/acid 4d6, 3 stat darts, slow dart, blind/confuse/poison/PARALYSIS gas 5-14 turns) (spells2.c:4919, object2.c:3829,4169, cmd1.c:891+)","COSTLY","never: GF_MAKE_TRAP sets no obvious (spells1.c:1894-1910)",U+"789")
a(S,"Trap/Door Destruction",10,"destroys adjacent doors/traps","HARMLESS","only if something destroyed",U+"990")
a(S,"Holy Chant",10,"bless 1d24+12","HARMLESS","if newly blessed",U+"953")
a(S,"Enchant Weapon To-Hit",15,"enchant wielded weapon to-hit +1 (prompt, scroll kept if cancelled)","GOOD","yes",U+"861")
a(S,"Enchant Weapon To-Dam",15,"enchant weapon to-dam +1","GOOD","yes",U+"868")
a(S,"Enchant Armor",15,"enchant one armour piece AC +1","GOOD","yes",U+"854")
a(S,"Summon Undead",15,"as Summon Monster (1-3, mean 1.9) but undead only, level dlv+5; undead can include ghoul(26)/ghast(30) paralyzers, no FA","DANGEROUS (LETHAL deeper)","only if undead placed",U+"776")
a(S,"Life",20,"restore_level + do_scroll_life (MAngband-specific; restores exp/stats)","GOOD","yes",U+"1038")
a(S,"Teleport Level",20,"50% down 1 level, else up 1 (town->down; up from dlv1 goes to town); 'Nothing happens' in ironman (spells1.c:365-395)","NUISANCE","yes",U+"809")
a(S,"Acquirement",20,"creates 1 great object at your feet (object2.c:3784); aware cost 100000","GOOD (jackpot)","yes",U+"1023")
a(S,"Holy Prayer",25,"bless 1d48+24","HARMLESS","if newly blessed",U+"959")
a(S,"*Identify*",30,"full ID of an item","GOOD","yes",U+"830")
a(S,"Protection from Evil",30,"prot evil 3*clvl+1d25 turns","HARMLESS","if newly set",U+"976")
a(S,"Recharging",40,"prompts for wand/staff; backfire chance 1/[(60+100-itemlvl-10*charges per item)/15], can destroy it; cancel keeps scroll (spells2.c:3093-3135)","COSTLY if used on wand/staff","yes",U+"889")
a(S,"Banishment",40,"prompts for monster symbol; deletes all non-unique of that char on level; 1d4 dmg per kill","HARMLESS/GOOD","yes (cancel keeps scroll)",U+"1009")
a(S,"Dispel Undead",40,"60 dmg to undead in LOS","HARMLESS","only if undead hit",U+"1003")
a(S,"*Destruction*",40,"destroy_area r15: deletes monsters+floor objects, scrambles terrain; you: 'searing blast of light', blind 11-20 turns (no resist unless blind/light res); player grid spared (spells2.c:3617-3680)","COSTLY (blind, loses floor loot)","yes",U+"996")
a(S,"*Remove Curse*",50,"uncurses everything incl. heavy curses","GOOD","yes",U+"847")
a(S,"Mass Banishment",50,"deletes all non-unique monsters within 20 squares, 1d3 dmg each","GOOD","yes",U+"1016")
a(S,"*Enchant Weapon*",50,"to-hit 1d3 and to-dam 1d3","GOOD","yes",U+"882")
a(S,"Curse Weapon",50,"wielded weapon becomes Shattered: to-hit and to-dam -(2..10) each, dice 0d0, CURSED+BROKEN => sticky, value 0 (artifact 50% save) (spells2.c:2255-2310)","COSTLY","yes if weapon wielded",U+"757")
a(S,"*Enchant Armor*",50,"AC +1d3+2","GOOD","yes",U+"875")
a(S,"Curse Armor",50,"body armour becomes Blasted: to_a -(2..10), base ac 0, CURSED+BROKEN => sticky, value 0 (spells2.c:2184-2250)","COSTLY","yes if body armour worn",U+"751")
T="staff"
a(T,"Treasure Location",5,"detect gold","GOOD","only if found",U+"1177")
a(T,"Object Location",5,"detect objects","GOOD","only if found",U+"1184")
a(T,"Light",5,"light room/radius 2","HARMLESS","yes",U+"1163")
a(T,"Cure Light Wounds",5,"heal 1d8","HARMLESS","only if HP restored",U+"1214")
a(T,"Detect Invisible",5,"detect invisible","HARMLESS","only if found",U+"1202")
a(T,"Darkness",5,"as scroll: blind 3+1d5 turns + unlight","NUISANCE","yes",U+"1089")
a(T,"Trap Location",10,"detect traps","HARMLESS","only if found",U+"1190")
a(T,"Summoning",10,"loop k<randint1(4): 1/2/3/4 monsters = 25/37.5/28/9% (mean 2.2), level dlv+5, groups allowed","DANGEROUS","only if monster placed",U+"1111")
a(T,"Haste Monsters",10,"all monsters in LOS get +10 speed (project_hack GF_OLD_SPEED; spells2.c:3202,3243)","DANGEROUS if monsters in view, else harmless","only if a monster seen",U+"1105")
a(T,"Slow Monsters",10,"-10 speed on LOS monsters (saving throw by level)","HARMLESS","only if monster seen",U+"1259")
a(T,"Sleep Monsters",10,"sleeps LOS monsters (save by level)","HARMLESS","only if monster seen",U+"1253")
a(T,"Door/Stair Location",10,"detect doors","HARMLESS","only if found",U+"1196")
a(T,"Perception (Identify)",10,"identify an item; cancel keeps charge","GOOD","yes",U+"1132")
a(T,"Teleportation",20,"teleport up to 100 (min 50)","HARMLESS","yes",U+"1124")
a(T,"Starlight",20,"light beams in 8 directions","HARMLESS","yes",U+"1152")
a(T,"Detect Evil",20,"detect evil monsters","HARMLESS","only if found",U+"1208")
a(T,"Enlightenment (map area)",20,"map_area local, not whole level","GOOD","yes",U+"1170")
a(T,"Curing",25,"cures blind/poison/conf/stun/cut","HARMLESS","only if something cured",U+"1220")
a(T,"Probing",30,"probe monsters in LOS","HARMLESS","yes",U+"1278")
a(T,"Earthquakes",40,"earthquake r10: 15% of grids hit; user stands at epicentre which is skipped, so the user is not hurt by own quake (spells2.c:3867-3990); monsters in hit grids take 4d8 or die","HARMLESS to user, alters map","yes",U+"1317")
a(T,"Speed",40,"haste +1d30+15 turns (+5 if already hasted)","GOOD","if not already hasted",U+"1265")
a(T,"Slowness",40,"slow -10 for 1d30+15 turns","NUISANCE (DANGEROUS if monsters near)","if slowed",U+"1099")
a(T,"Remove Curse",40,"as scroll","GOOD","only if uncursed something",U+"1139")
a(T,"*Destruction*",50,"as scroll: blind 11-20 turns, wipes r15","COSTLY","yes",U+"1325")
a(T,"Dispel Evil",50,"60 dmg to evil in LOS","HARMLESS","only if hit",U+"1285")
W="wand"
a(W,"Light",3,"lite_line in direction","HARMLESS","yes always",U+"1455")
a(W,"Heal Monster",3,"heals target 4d6, wakes it","NUISANCE","only if monster seen",U+"1413")
a(W,"Haste Monster",3,"target +10 speed permanent (cap 150)","DANGEROUS","only if monster seen",U+"1419")
a(W,"Magic Missile",3,"3d4 bolt","GOOD","yes always (ident set regardless of hit)",U+"1507")
a(W,"Wonder",3,"random sval 0..23: 3/24 bad (Heal/Haste/Clone), rest any wand up to cold ball; no dragon/annihilation","NUISANCE/DANGEROUS","when sub-effect identifies",U+"1408")
a(W,"Slow Monster",5,"slow target (save by level)","HARMLESS","only if seen/obvious",U+"1469")
a(W,"Confuse Monster",5,"confuse target","HARMLESS","only if seen/obvious",U+"1475")
a(W,"Sleep Monster",5,"sleep target","HARMLESS","only if seen/obvious",U+"1463")
a(W,"Stinking Cloud",5,"12 poison ball rad 2","GOOD","yes always",U+"1499")
a(W,"Stone to Mud",10,"dissolves wall","GOOD","only if wall dissolved",U+"1449")
a(W,"Trap/Door Destruction",10,"destroy door in line","HARMLESS","only if door destroyed",U+"1443")
a(W,"Scare Monster",10,"fear target","HARMLESS","only if seen/obvious",U+"1481")
a(W,"Lightning Bolts",15,"6d6 bolt/beam","GOOD","yes always",U+"1523")
a(W,"Clone Monster",15,"clvl>=10: NO clone, but target fully healed and +10 speed; clvl<10: also spawns a copy (spells2.c:4801-4823, spells1.c:2770-2800)","NUISANCE (DANGEROUS below clvl 10)","only if monster seen",U+"1425")
a(W,"Frost Bolts",20,"6d8 bolt","GOOD","yes always",U+"1539")
a(W,"Polymorph",20,"target becomes a new monster (poly_r_idx), unique immune, save randint1(90)>mlvl; new monster is fresh and may be tougher (spells1.c:3264-3300)","NUISANCE","only if changed",U+"1493")
a(W,"Teleport Other",20,"teleports target away","GOOD","only if monster seen",U+"1431")
a(W,"Disarming",20,"disarms trap","HARMLESS","only if trap",U+"1437")
a(W,"Fire Bolts",30,"12d8 bolt","GOOD","yes always",U+"1531")
a(W,"Acid Bolts",30,"10d8 bolt","GOOD","yes always",U+"1515")
a(W,"Lightning Balls",35,"64 ball","GOOD","yes always",U+"1555")
a(W,"Cold Balls",40,"96 ball","GOOD","yes always",U+"1571")
a(W,"Drain Life",50,"150 dmg to living","GOOD","only if hit",U+"1487")
a(W,"Fire Balls",50,"144 ball","GOOD","yes always",U+"1563")
a(W,"Acid Balls",50,"120 ball","GOOD","yes always",U+"1547")
a(W,"Dragon's Flame",50,"200 fire ball rad 3","GOOD","yes always",U+"1585")
a(W,"Dragon's Frost",50,"160 cold ball rad 3","GOOD","yes always",U+"1593")
D="rod"
a(D,"Trap Location",5,"detect traps","HARMLESS","only if found",U+"1726")
a(D,"Light",10,"lite_line","HARMLESS","yes always",U+"1835")
a(D,"Door/Stair Location",15,"detect doors","HARMLESS","only if found",U+"1732")
a(D,"Illumination",20,"lite_area","HARMLESS","yes always",U+"1752")
a(D,"Lightning Bolts",20,"6d6","GOOD","yes always",U+"1875")
a(D,"Frost Bolts",25,"10d8","GOOD","yes always",U+"1891")
a(D,"Recall",30,"starts recall like scroll; zap again to cancel","NUISANCE","yes always",U+"1745")
a(D,"Fire Bolts",30,"16d8","GOOD","yes always",U+"1883")
a(D,"Slow Monster",30,"slow target","HARMLESS","only if effect obvious",U+"1849")
a(D,"Sleep Monster",30,"sleep target","HARMLESS","only if obvious",U+"1843")
a(D,"Detection",30,"detection() everything nearby","GOOD","yes always",U+"1766")
a(D,"Polymorph",35,"as wand","NUISANCE","only if changed",U+"1861")
a(D,"Disarming",35,"disarm trap","HARMLESS","only if trap",U+"1829")
a(D,"Probing",40,"probe","HARMLESS","yes",U+"1773")
a(D,"Acid Bolts",40,"12d8","GOOD","yes always",U+"1867")
a(D,"Teleport Other",45,"teleport target away","GOOD","only if monster hit",U+"1823")
a(D,"Perception (Identify)",50,"identify item","GOOD","yes",U+"1738")
N="ring"
cx="cmd3.c:501-509 (worn cursed => 'Oops! It feels deathly cold!', ID_SENSE, sticky cmd3.c:642,373)"
a(N,"Aggravate Monster",5,"CURSED always (LIGHT_CURSE, object2.c:170): monsters notice/wake without the usual 1/1024 roll (melee2.c:2503-2518); sticky until Remove Curse; value 0","DANGEROUS","no (wear never calls object_aware)",cx)
a(N,"Weakness",5,"CURSED: STR -(1+m_bonus(5)); sticky","COSTLY","no",cx)
a(N,"Stupidity",5,"CURSED: INT -(1+m_bonus(5)); sticky; warrior barely cares but slot blocked","NUISANCE","no",cx)
a(N,"Teleportation",5,"CURSED: 1%/player-begin tick random teleport range 40 (dungeon.c:990-994); sticky","NUISANCE/DANGEROUS","no",cx)
a(N,"Searching",5,"may be cursed (negative) per apply_magic: ~13-24% at dlv 5-30","HARMLESS/NUISANCE","no","object2.c:2741")
a(N,"Slow Digestion/Feather Falling/Resist Fire/Resist Cold",5,"harmless; never cursed (no power<0 branch)","HARMLESS","no",U+"n/a")
a(N,"Protection",10,"+AC; cursed variant (power<0) -AC, sticky","GOOD / COSTLY if cursed","no","object2.c:2850")
a(N,"Free Action",20,"FREE_ACT; never cursed branch","GOOD","no (EASY_KNOW only after aware)","object.txt N:144")
a(N,"Damage",20,"+dam; cursed variant negative","GOOD / COSTLY if cursed","no","object2.c:2806")
a(N,"Accuracy",20,"+hit; cursed variant negative","GOOD / COSTLY if cursed","no","object2.c:2828")
a(N,"Sustain x6",20,"sustains","HARMLESS","no","object.txt N:156-161")
a(N,"Strength/Dex/Con/Int",30,"pval 1+m_bonus(5); cursed variant negative pval","GOOD / COSTLY if cursed","no","object2.c:2686")
a(N,"See Invisible",30,"see invis","HARMLESS","no","object.txt N:155")
a(N,"Resist Poison",40,"res pois","GOOD","no","object.txt N:143")
a(N,"Slaying",40,"+hit/+dam; cursed variant negative","GOOD / COSTLY","no","object2.c:2872")
a(N,"Flames/Acid/Ice/Lightning",50,"+AC resist, activation","GOOD","no","object2.c:2763")
a(N,"Woe",50,"CURSED: teleport + WIS/CHR -(1+m_bonus(5)) + to_a -(5+m_bonus(10)); sticky","DANGEROUS","no","object2.c:2790")
M="amulet"
a(M,"Teleportation",10,"CURSED always: random teleport 1%/tick, range 40; sticky","NUISANCE/DANGEROUS","no",cx)
a(M,"Resist Acid/Adornment/Resist Lightning",10,"harmless, never cursed","HARMLESS","no","object.txt N:168-169")
a(M,"Infravision",10,"+infra; cursed variant negative","HARMLESS/NUISANCE","no","object2.c:3048")
a(M,"Searching",15,"cursed variant negative","HARMLESS","no","object2.c:2927")
a(M,"Slow Digestion",15,"harmless","HARMLESS","no","object.txt N:167")
a(M,"Wisdom/Charisma",30,"cursed variant negative pval","HARMLESS (warrior)","no","object2.c:2905")
a(M,"Regeneration",30,"regen","GOOD","no","object.txt:3756")
a(M,"Speed",30,"+1..3 speed; cursed variant negative speed","GOOD / DANGEROUS if cursed","no","object2.c:2970")
a(M,"the Moon/Terken",40,"never cursed","GOOD","no","object2.c:2993,3003")
a(M,"DOOM",50,"ALWAYS cursed: all 6 stats -(1d5+m_bonus(5)), to_a negative; sticky","LETHAL-ish (stat crash)","no","object2.c:3069")
a(M,"ESP",50,"never cursed; telepathy","GOOD","no","object2.c:2948")
w=csv.writer(open('/projectnb/jbrcs/mangband/Advisor/studies/2026-10-07-selling/scratch/D_devices.csv','w'))
w.writerow("tval,kind,level,effect,class,aware_on_use,cite".split(','))
for r in R: w.writerow(r)
print(len(R))
