import csv

ratings = [
# (danger, response, threats, neutraliser, safe_when, notes)
(0,"FIGHT","none (0 dmg blows: BEG + EAT_GOLD)","none","always","harmless, steals gold only"),
(0,"FIGHT","CLAW 1d1","none","always",""),
(0,"FIGHT","BITE 1d1","none","always",""),
(0,"FIGHT","none - both blows are MOAN (0 dmg, message only)","none","always","UNIQUE HP350 but cannot damage the player [SEEN monster.txt:145-146]; paper-tiger unique"),
(0,"FIGHT","DROOL (0 dmg)","none","always",""),
(0,"FIGHT","DROOL (0 dmg)","none","always",""),
(0,"FIGHT","DROOL (0 dmg)","none","always",""),
(0,"FIGHT","BEG (0 dmg)","none","always",""),
(0,"FIGHT","BEG (0 dmg)","none","always",""),
(2,"FIGHT","HIT 1d6=6; EAT_ITEM steals gear","kill fast (limits exposure to theft)","always","classic early thief"),
(0,"FIGHT","BEG (0 dmg)","none","always",""),
(0,"FIGHT","HIT 1d3=3; alertness 255 (ignores player)","none","always","essentially never attacks first"),
(3,"CAREFUL","HIT 1d10=avg5.5,max10 vs clvl1 HP~10","more HP before engaging","clvl3+/HP30+","already-known 'matters only to brand-new characters' confirmed: 1 hit can nearly kill a fresh clvl1 [1d10 max ~= clvl1 HP]"),
(3,"CAREFUL","HIT 2d6=avg7,max12 vs clvl1 HP~10","more HP before engaging","clvl3+/HP30+","stronger sibling of mercenary, same early spike risk"),
(1,"FIGHT","2xSPORE 1d4=avg5","none","always","stationary"),
(2,"FIGHT","SPORE:CONFUSE 1d4 + confuse status (no resist early)","stationary - can be avoided","always","confusion can interrupt bot loop but low dmg"),
(1,"FIGHT","BITE+STING=6","none","always",""),
(1,"FIGHT","BITE+STING=4","none","always",""),
(1,"FIGHT","TOUCH 1d2","none","always",""),
(2,"FIGHT","TOUCH 1d2; INVISIBLE","See Invisible","always","trivial dmg but unseen"),
(2,"CAREFUL","BITE 1d2; MULTIPLY breeder","kill immediately before it breeds","always",""),
(1,"FIGHT","BITE+CRUSH=7","none","always",""),
(0,"FIGHT","BITE+CRUSH=2","none","always",""),
(1,"FIGHT","HIT 1d5","none","always",""),
(1,"FIGHT","HIT 1d8","none","always",""),
(2,"CAREFUL","CRAWL:POISON 1d2; MULTIPLY","kill immediately","always","poison bypasses AC, tiny dice"),
(2,"CAREFUL","GAZE:PARALYZE, 0 dmg; only ~5% hit chance (flat floor - formula i=2+lvl*3=5 never exceeds ac*3/4)","Free Action; or never melee it (NEVER_MOVE -> walk around = zero risk)","always unless FA","[SEEN melee1.c:106-127 + monster.txt:392 'B:GAZE:PARALYZE' no dice] deals ZERO direct damage, cannot kill alone - tempers the 'melee=death' folklore"),
(0,"FIGHT","BITE 1d1","none","always",""),
(3,"CAREFUL","BITE1d1 but FRIENDS pack vs clvl1 HP~10","corridor (limits simultaneous attackers)","clvl3+/HP30+ or corridor","classic pack-swarm risk despite trivial per-hit dmg"),
(1,"FIGHT","BITE 1d2","none","always",""),
(1,"FIGHT","BITE 1d1; speed+10","none","always","fast but trivial dmg"),
(2,"FIGHT","SHRIEK spell calls other monsters; NEVER_BLOW (cannot melee you at all)","kill it quickly to stop the shrieking","always","zero direct danger; risk is only what it summons/wakes nearby"),
(1,"FIGHT","CRAWL:POISON1d4+EAT_FOOD","none","always",""),
(0,"FIGHT","CRAWL1d1","none","always",""),
(2,"FIGHT","2xHIT1d7=avg8","none","always","moderate solo melee"),
(2,"FIGHT","HIT1d6+EAT_GOLD","kill fast to limit theft","always",""),
(3,"CAREFUL","CAUSE_1 3d8=avg13.5 mostly unsaved (save~16-30%); HEAL prolongs fight","HP40+ buffer; kill fast","HP40+","1/12 cast but ~13.5 dmg vs dl2 HP20-30 is a big chunk; contradicts 'already-known summon' claim: spells are HEAL|SCARE|CAUSE_1, no summon"),
(3,"CAREFUL","MISSILE 2d6+lvl/3=avg7.7; BLIND+CONF status locks; BLINK denies quick kill","kill fast (no resist_blind/conf early)","HP40+","confirms BLINK (already-known) but no summon spell present"),
(2,"FIGHT","SPORE:TERRIFY1d6; fear status","stationary - avoidable","always","low dmg, fear interrupts combat loop"),
(1,"FIGHT","TOUCH:POISON1d2","none","always","tanky HP64 but weak attack"),
(1,"FIGHT","BITE1d3","none","always",""),
(1,"FIGHT","BITE1d4","none","always",""),
(1,"FIGHT","BITE:FIRE1d3","none","always",""),
(1,"FIGHT","3 blows=avg4","none","always",""),
(1,"FIGHT","HIT1d5","none","always",""),
(3,"CAREFUL","BITE1d4; speed+10 (acts ~2x/player turn)","clvl4+/HP40+ or corridor","clvl4+","already-known 'fast early killer' - speed not raw dmg is the threat; itself dies fast (HP25)"),
(3,"CAREFUL","BITE1d4; speed+10","clvl4+/HP40+","clvl4+","twin of Grip; if both spawn together dmg doubles"),
(2,"CAREFUL","CRAWL:ACID1d3; MULTIPLY","kill immediately","always",""),
(2,"FIGHT","BITE+CRUSH=avg6","none","always",""),
(3,"CAREFUL","BITE1d4; FRIENDS pack; speed+10","corridor","clvl4+ or corridor","spider-swarm risk like jackals"),
(2,"FIGHT","2xCLAW1d3=avg6; speed+10","none","always",""),
(2,"AVOID","TOUCH:EAT_GOLD1d4; INVISIBLE; speed+20 (3x energy); steals then blinks away","See Invisible to catch him; otherwise accept gold loss","always","fast invisible gold thief, not a combat threat (melee_max=4, HP400 makes him near-unkillable anyway)"),
(1,"FIGHT","CRAWL:ACID1d3","none","always",""),
(2,"FIGHT","TOUCH:TERRIFY (0 dmg); INVISIBLE; PASS_WALL; speed+20","See Invisible","always","zero direct damage (melee_max=0); only fear+disruption, cannot kill alone"),
(0,"FIGHT","CRAWL1d2","none","always",""),
(2,"CAREFUL","BITE1d1; MULTIPLY breeder","kill fast, don't dawdle","always","already-known breeder; trivial individually"),
(1,"FIGHT","CRUSH1d8=avg4.5","none","always",""),
(2,"FIGHT","SPORE:POISON2d4=avg5 (bypasses AC)","stationary - avoidable","always",""),
(2,"FIGHT","2xEAT_LITE1d3=avg6; drains light-source fuel","spare light source","always","tanky HP80"),
(1,"FIGHT","TOUCH:POISON1d3","none","always",""),
(2,"FIGHT","HIT1d4+EAT_GOLD","kill fast","always",""),
(1,"FIGHT","BITE1d4","none","always",""),
(1,"FIGHT","SPORE1d4","none","always","tanky HP64"),
(0,"FIGHT","CRAWL1d2","none","always",""),
(2,"CAREFUL","CRAWL:LOSE_DEX1d3; MULTIPLY; permanent DEX drain (no sustain early)","kill fast; Restore Dex potion","always","stat drain + breeder combo"),
(3,"AVOID","CRAWL:POISON1d2; INVISIBLE + MULTIPLY (silent, unseen swarm)","See Invisible","always","invisible breeder - colony can grow undetected since you cannot target what you cannot see"),
(2,"CAREFUL","GAZE:LOSE_STR1d6; power=0 so mostly only the flat 5% hit-floor connects","Restore Str potion; or avoid melee (NEVER_MOVE)","always","same 'eye-family low-power-gaze' pattern as floating eye - rare real STR-drain procs"),
(1,"FIGHT","BITE1d5","none","always",""),
(3,"CAREFUL","2xHIT1d5=avg5; MISSILE 2d6+lvl/3=avg8.3; ARROW_1 (formula not in A1 legend)","HP60+","HP60+","ranged spell adds to melee; ARROW_1 dmg formula unconfirmed - lead"),
(3,"CAREFUL","2xHIT1d7=avg8; CAUSE_1 3d8=avg13.5 mostly unsaved; SCARE","HP60+","HP60+",""),
(1,"FIGHT","TOUCH:COLD1d6","none","always","tanky HP96"),
(2,"FIGHT","HIT1d4+TOUCH:POISON2d4=avg9; ambush mimic, CAN move/bash doors","none","always","not NEVER_MOVE - can chase, unlike a purely static 'treasure trap' assumption"),
(2,"CAREFUL","BITE:POISON1d3; MULTIPLY","kill fast","always",""),
(2,"CAREFUL","CRAWL:COLD1d4; MULTIPLY","kill fast","always",""),
(1,"FIGHT","BITE+CRUSH=avg7.5","none","always",""),
(3,"CAREFUL","2xHIT1d8=avg9; speed+10 (~2x/player turn, ~18 effective/turn)","HP60+ or corridor","clvl6+/HP60+","already-known early unique threat, confirmed by melee output+speed"),
(3,"AVOID","pack of BLIND/CONF/MISSILE casters (FRIENDS)","corridor; no resist_blind/conf early","HP70+ or corridor","group caster: multiple simultaneous status-locks + missile dmg"),
(2,"FIGHT","CRUSH1d8+SPIT:ACID2d6=avg11.5 (acid bypasses AC)","none","always",""),
(1,"FIGHT","CRAWL:COLD1d4","none","always",""),
(1,"AVOID","TOUCH:EAT_FOOD1d1; INVISIBLE; PASS_WALL","See Invisible","always","near-zero combat threat, just eats food supply"),
(1,"FIGHT","TOUCH:ACID1d2","none","always","HP176 - very tanky for 1d2 dmg, a time sink not a threat [surprise]"),
(2,"FIGHT","HIT1d10=avg5.5,max10","none","always","high-variance single blow"),
(1,"FIGHT","HIT1d6","none","always",""),
(1,"FIGHT","TOUCH1d5","none","always",""),
(2,"CAREFUL","GAZE:UN_BONUS (0 direct dmg, power=20 -> real proc chance) - disenchants gear","resist_disen; or avoid melee (NEVER_MOVE)","always","unlike floating eye, power=20 means the to-hit formula (not just the 5% floor) can land - permanent gear damage risk, no HP risk"),
(2,"CAREFUL","CRAWL:FIRE1d6; MULTIPLY","kill fast","always",""),
(1,"FIGHT","BITE:POISON2d4=avg5","none","always",""),
(2,"FIGHT","3xSPORE:LOSE_CON1d2 (triple stat-drain blow) but only 1 HP itself","Restore Con potion; kill on sight (dies to 1 hit)","always","dies almost immediately (1 HP) so real exposure is at most one exchange"),
(3,"AVOID","pack of CAUSE_1 3d8 casters (FRIENDS) + HEAL","corridor; HP70+","HP70+ or corridor","group version of Novice priest #37 - stacking unsaved ~13.5 avg hits"),
(3,"CAREFUL","pack of 2xHIT1d7 melee (FRIENDS)","corridor","corridor or HP70+","group melee, can gang up in open rooms"),
(2,"CAREFUL","pack of thieves (FRIENDS), HIT1d6+EAT_GOLD","corridor","always",""),
(2,"FIGHT","SPORE:CONFUSE1d4 unresisted; HP120 (long fight = many confuse rolls)","resist_conf; or avoid (NEVER_MOVE)","always","confusion-lock risk over a long grind, not lethal alone"),
(1,"FIGHT","BITE1d3; speed+20","none","always",""),
(2,"CAREFUL","HIT1d9; ARROW_2 spell 1/5 freq (formula not in A1 legend)","none","always","ARROW_2 dmg unconfirmed - lead"),
(2,"FIGHT","HIT1d6+TOUCH:POISON2d6=avg10.5; can move/bash doors","none","always",""),
(2,"CAREFUL","HIT1d8; FRIENDS pack","corridor","corridor","weak orc but pack"),
(1,"FIGHT","BITE:POISON2d5=avg6","none","always",""),
(3,"CAREFUL","HIT1d8; FRIENDS pack of orcs","corridor","corridor or HP80+","orc-pit style swarm risk"),
(3,"CAREFUL","BITE+STING:POISON=avg4.5; FRIENDS pack; poison bypasses AC","corridor","corridor","pack + poison combo"),
(2,"CAREFUL","HIT1d8; FRIENDS demon pack","corridor","corridor",""),
(3,"AVOID","GAZE:BLIND2d6=avg7 + real blind lock (power2, i=2+7*3=23, connects unlike floating eye)","resist_blind; or avoid melee entirely (NEVER_MOVE)","always","real dice dmg + higher power/level -> meaningfully higher proc rate; long blind (10+d7) is a serious lock"),
(2,"CAREFUL","CRUSH1d10+BITE:LOSE_STR1d4=avg9.5; permanent STR drain","Restore Str","always",""),
(3,"AVOID","TOUCH:LOSE_STR1d5; HP208 (huge - many drain-attempts over the necessarily long fight)","avoid melee entirely (NEVER_MOVE); Restore Str/sustain Str","always","extreme HP for tiny per-hit dmg forces a long grind; each of its turns is another STR-drain roll"),
(2,"CAREFUL","BITE:LOSE_STR2d4=avg5","Restore Str","always",""),
(1,"FIGHT","TOUCH:ACID2d5=avg5.5 (bypasses AC)","none","always",""),
(1,"FIGHT","2xHIT1d2=avg2","none","always",""),
(2,"FIGHT","HIT2d2+TOUCH:LOSE_WIS; INVISIBLE; PASS_WALL","See Invisible","always","low dmg, mostly a WIS-drain nuisance"),
(2,"CAREFUL","2xHIT1d6=avg7; CONF spell (unresisted, skill_sav only)","resist_conf; HP70+","always",""),
(1,"FIGHT","2xBITE1d6=avg7","none","always",""),
(4,"LEAVE","3xHIT1d10=avg16.5; ESCORT+ESCORTS bring a kobold group; HP150","AVOID/LEAVE unless well-geared","clvl10+/HP100+ with allies present","already-known early unique threat, confirmed - group amplifies an already-solid melee output"),
(4,"LEAVE","BO_COLD 6d8+lvl/3=avg23 (unresisted); BA_POIS 2d12=avg13; HEAL prolongs; SLOW denies FA-less character","rCold, rPois, Free Action (vs SLOW)","clvl12+/HP120+ with resists","already-known early unique threat, confirmed and sharpened by spell kit"),
(4,"LEAVE","4 blows(1d10,1d10,1d9,1d9)=avg19; ESCORT brings orcs; HP190","AVOID/LEAVE","clvl10+/HP100+ with allies present","highest sustained melee among the escort uniques in this band"),
(1,"FIGHT","HIT1d6","none","always",""),
(3,"AVOID","pack of MISSILE/ARROW casters (FRIENDS)","corridor; HP90+","corridor or HP90+",""),
(3,"CAREFUL","BITE:FIRE3d6=avg10.5 (bypasses AC) + BR_FIRE hp/3=avg14 (both fire, unresisted)","Resist Fire","always","fire bite+breath both bypass AC; rFire nearly neutralises"),
(1,"FIGHT","SPORE:TERRIFY1d4","none","always","tanky HP168"),
(1,"FIGHT","HIT2d5=avg6","none","always",""),
(3,"AVOID","pack of CAUSE_1 casters (FRIENDS)","corridor; HP90+","corridor or HP90+",""),
(2,"CAREFUL","HIT1d8; FRIENDS demon pack","corridor","corridor",""),
(3,"CAREFUL","HIT1d10; FRIENDS orc pack","corridor","corridor or HP90+","orc-pit swarm risk"),
(2,"CAREFUL","HIT2d4+EAT_ITEM (steals real gear, not just gold)","kill fast to prevent item loss","always",""),
(1,"FIGHT","3 blows=avg5","none","always",""),
(1,"FIGHT","TOUCH+CRAWL:ACID=avg7","none","always",""),
(2,"CAREFUL","BITE:POISON1d4; MULTIPLY","kill fast","always",""),
(1,"FIGHT","3 blows=avg4.5","none","always",""),
(3,"CAREFUL","2xHIT1d6=avg7; CAUSE_1 avg13.5 mostly unsaved; MISSILE avg10; BLINK escape","HP100+","HP100+",""),
(3,"CAREFUL","BR_ELEC hp/3=avg33 (unresisted, breaths bypass AC); 3 claws/bite=avg7","Resist Electricity","HP130+ or rElec","breath ~33 vs HP100-150 char is a serious single hit"),
(3,"CAREFUL","BR_COLD hp/3=avg33","Resist Cold","HP130+ or rCold",""),
(3,"CAREFUL","BR_POIS hp/3=avg33 (cap800 n/a) + poisons if unresisted","Resist Poison","HP130+ or rPois",""),
(3,"CAREFUL","BR_ACID hp/3=avg33 + degrades armor/inventory","Resist Acid","HP130+ or rAcid",""),
(3,"CAREFUL","BR_FIRE hp/3=avg33","Resist Fire","HP130+ or rFire",""),
(1,"FIGHT","BITE+STING:LOSE_STR=avg4.5","none","always",""),
(4,"LEAVE","4xHIT1d12=avg26 (melee_max48, highest in band); HP210, no spells/escort","AVOID/LEAVE","clvl13+/HP150+","single hardest-hitting pure-melee unique in this band"),
(3,"CAREFUL","SPIT:BLIND1d2 (real blind proc, power2, i=29) + BITE:POISON3d4=avg7 unresisted","resist_blind; kill fast","always","blind+poison combo"),
(3,"CAREFUL","4 blows incl 2xPOISON1d6, combined avg18/turn, 2 of 4 bypass AC","HP130+","HP130+",""),
(4,"LEAVE","BA_POIS 2d12=avg13 (unresisted) + MISSILE avg10 + BLIND + CONF; 1/5 (20%) cast freq","Resist Poison; resist_blind/conf; HP130+","HP130+ with resists","far nastier than plain 'Dark elf' - upgraded to a high-frequency multi-effect caster; most dangerous non-unique in the whole band"),
(4,"LEAVE","1/4 (25%) cast freq: TELE_TO (drags you to him, defeats simply walking away); S_MONSTER summon; SLOW; CONF; HEAL; ESCORT+ESCORTS yeek group","Free Action (vs SLOW); resist_conf; kill fast before summon reinforces","clvl13+/HP150+","only summoner in this band; TELE_TO undermines AVOID-by-walking-away"),
(2,"FIGHT","2xHIT1d8=avg9","none","always",""),
(2,"FIGHT","SPORE1d1 (trivial); INVISIBLE+MULTIPLY","See Invisible","always","invisible breeder like Clear worm mass but far weaker dmg (1d1) and only 1 HP"),
(4,"LEAVE","4 blows(1d12,1d10,1d12,1d10)=avg22 (melee_max44, 2nd-highest in band); ESCORT brings orcs; HP230","AVOID/LEAVE","clvl13+/HP150+","already-known early unique threat, confirmed - near-Brodda melee output plus an escort"),
(2,"CAREFUL","BITE:POISON2d6=avg7 (bypasses AC)","none","always",""),
(1,"FIGHT","SPORE:POISON1d3","none","always","tanky HP120"),
(2,"CAREFUL","SPORE:UN_BONUS1d6; disenchants gear","resist_disen; avoid melee (NEVER_MOVE)","always",""),
(4,"LEAVE","BR_LITE/BR_DARK hp/6=avg33 (weaker-resist type K=4, still unresisted early) + blind; CONF+SCARE spells; HP200","resist_lite/dark + resist_blind; HP150+","HP150+ with resists","multi-effect caster+breath+high HP, more dangerous than the baby dragons of the same depth"),
(3,"CAREFUL","1/3 (33%!) cast freq BLINK|TELE_TO; HIT1d8=avg4.5 melee is mild","kill fast before repeated TELE_TO drags you off-course","always","very high TELE_TO frequency can pull the character away from a stair-scum position - operationally dangerous even though direct dmg is low"),
(2,"CAREFUL","HIT2d5+TOUCH:POISON3d5=avg13; can move/bash doors (not a static trap)","none","always",""),
(3,"CAREFUL","BITE1d6; FRIENDS pack; speed+10","corridor","corridor or HP130+","fast wolf-pack risk, classic Angband peril"),
(2,"CAREFUL","BITE1d2; MULTIPLY; speed+10 (breeds and moves fast)","kill immediately, worst breeder tempo in band","always",""),
(3,"CAREFUL","2xCLAW1d8=avg9; speed+10 (~1.5-2x turns, ~14-18 effective/turn)","HP130+","HP130+","fast heavy hitter, solo but can burst"),
(2,"CAREFUL","HIT2d4+EAT_ITEM (steals gear)","kill fast","always",""),
(2,"CAREFUL","BITE:EAT_LITE1d2; MULTIPLY","kill fast; spare light fuel","always",""),
(1,"FIGHT","EAT_FOOD2d3+LOSE_CHR2d3=avg8.5 (CHR loss cosmetic)","none","always","tanky HP160 but weak/cosmetic attack"),
(1,"FIGHT","2xBITE1d3=avg4","none","always",""),
(1,"FIGHT","2xBITE1d4=avg5","none","always",""),
(2,"FIGHT","3 blows=avg10.5","none","always",""),
(3,"CAREFUL","BR_CONF hp/6=avg17 + confuses (unresisted); 3 claws/bite=avg7","resist_conf","HP100+","confusion-lock breath, not just raw damage"),
(3,"CAREFUL","BR_SOUN hp/6=avg17 + stun (unresisted); 3 claws/bite=avg7","resist_sound","HP100+","stun-lock breath"),
(2,"CAREFUL","3 blows=avg6; speed+10","none","always",""),
(3,"CAREFUL","CAUSE_1 3d8=avg13.5 mostly unsaved at dl3 (save~16-20%); HIT1d8; MISSILE avg8; 1/5 (20%) cast freq","HP40+","HP40+","punches well above its depth - 20% chance of a near-half-HP hit on a fresh clvl3 diver"),
]

with open('/projectnb/jbrcs/mangband/Advisor/studies/2026-09-27-danger-table/scratch/B1_input.csv') as f:
    rows = list(csv.DictReader(f))

assert len(rows) == len(ratings), (len(rows), len(ratings))

out_rows = []
for row, rt in zip(rows, ratings):
    danger, response, threats, neutraliser, safe_when, notes = rt
    out_rows.append({
        'idx': row['idx'],
        'name': row['name'],
        'level': row['level'],
        'symbol': row['symbol'],
        'color': row['color'],
        'danger': danger,
        'response': response,
        'threats': threats,
        'neutraliser': neutraliser,
        'safe_when': safe_when,
        'notes': notes,
    })

outpath = '/projectnb/jbrcs/mangband/Advisor/studies/2026-09-27-danger-table/scratch/B1_table.csv'
with open(outpath, 'w', newline='') as f:
    w = csv.DictWriter(f, fieldnames=['idx','name','level','symbol','color','danger','response','threats','neutraliser','safe_when','notes'], quoting=csv.QUOTE_MINIMAL)
    w.writeheader()
    for r in out_rows:
        w.writerow(r)

print("wrote", len(out_rows), "rows to", outpath)

# quick tally for dispatch
from collections import Counter
c = Counter(r['danger'] for r in out_rows)
print("danger distribution:", dict(sorted(c.items())))
fours = [r['name'] for r in out_rows if r['danger']==4]
print("danger4:", fours)
fives = [r['name'] for r in out_rows if r['danger']==5]
print("danger5:", fives)
